"""CLI entry point: podcraft init / publish / script / feed."""

import json
import shutil
from pathlib import Path

import click

from .config import PodcraftConfig, load_config, CONFIG_FILENAME, DEFAULT_VOICES

TEMPLATES_DIR = Path(__file__).parent / "templates"


@click.group()
@click.version_option(package_name="podcraft")
def main():
    """PodCraft - Turn any Markdown into a two-person dialogue podcast."""
    pass


@main.command()
@click.option("--language", "-l", default="en", help="Podcast language (en, zh, ja)")
@click.option("--title", "-t", default="My Podcast", help="Podcast title")
def init(language: str, title: str):
    """Initialize a new PodCraft project in the current directory."""
    config_path = Path.cwd() / CONFIG_FILENAME
    if config_path.exists():
        click.echo(f"  {CONFIG_FILENAME} already exists. Aborting.")
        return

    lang_short = language[:2]
    voices = DEFAULT_VOICES.get(lang_short, DEFAULT_VOICES["en"])

    if lang_short == "zh":
        host_name, guest_name = "小刘", "美美"
        desc = f"由 PodCraft 生成的播客。"
    elif lang_short == "ja":
        host_name, guest_name = "タロウ", "ハナコ"
        desc = f"PodCraftで生成されたポッドキャスト。"
    else:
        host_name, guest_name = "Alex", "Sam"
        desc = f"A podcast generated by PodCraft."

    config_content = f"""podcast:
  title: "{title}"
  description: "{desc}"
  author: ""
  language: "{language}"
  category: "Technology"
  link: ""
  cover_url: ""

hosts:
  host:
    name: "{host_name}"
    voice: "{voices['host']}"
  guest:
    name: "{guest_name}"
    voice: "{voices['guest']}"

llm:
  engine: "gemini"       # gemini, anthropic, openai, auto
  model: ""              # empty = default per engine
  temperature: 0.7

tts:
  engine: "edge"         # edge (free), volcano_podcast (paid, high quality)
  silence_duration: 1.5
  sample_rate: 44100
  bitrate: "192k"

feed:
  audio_base_url: ""     # URL where your MP3s are hosted
  output: "podcast-feed.xml"

paths:
  output: "output/"
  scripts: "scripts/"
  prompts: "prompts/"
"""
    config_path.write_text(config_content, encoding="utf-8")

    # Create directories
    for d in ["output", "scripts", "prompts", "episodes"]:
        (Path.cwd() / d).mkdir(exist_ok=True)

    # Copy language-appropriate prompt template
    src_template = TEMPLATES_DIR / f"system_{lang_short}.md"
    if not src_template.exists():
        src_template = TEMPLATES_DIR / "system_en.md"
    dst_template = Path.cwd() / "prompts" / "system.md"
    shutil.copy2(src_template, dst_template)

    click.echo(f"  Initialized PodCraft project ({language})")
    click.echo(f"  Created: {CONFIG_FILENAME}, prompts/system.md")
    click.echo(f"\n  Next steps:")
    click.echo(f"  1. Export your LLM API key: export GEMINI_API_KEY=...")
    click.echo(f"  2. Put a Markdown file in episodes/")
    click.echo(f"  3. Run: podcraft publish episodes/your-doc.md")


@main.command()
@click.argument("input_file")
@click.option("--title", "-t", default="", help="Episode title")
@click.option("--episode-num", "-n", type=int, default=0, help="Episode number")
@click.option("--focus", "-f", default="", help="Focus areas for script generation")
def publish(input_file: str, title: str, episode_num: int, focus: str):
    """Publish a podcast episode from a Markdown file."""
    from .pipeline import publish as run_publish

    config, root = load_config()
    run_publish(input_file, config, root, title, episode_num, focus)


@main.command()
@click.argument("input_file")
@click.option("--output", "-o", default="", help="Output script path")
@click.option("--focus", "-f", default="", help="Focus areas")
def script(input_file: str, output: str, focus: str):
    """Generate a dialogue script from a Markdown file (no audio)."""
    from .script import generate_script as gen_script
    from .utils import read_document, slugify

    config, root = load_config()
    paths = config.resolve_paths(root)
    scripts_dir = paths["scripts"]
    scripts_dir.mkdir(parents=True, exist_ok=True)

    content = read_document(input_file)
    if len(content) > 120000:
        content = content[:120000]

    click.echo(f"Generating script from {input_file} ({len(content)} chars)...")
    dialogue = gen_script(content, config, root, focus)

    if output:
        out_path = Path(output)
    else:
        slug = slugify(Path(input_file).stem)
        out_path = scripts_dir / f"{slug}_script.json"

    out_path.write_text(json.dumps(dialogue, ensure_ascii=False, indent=2), encoding="utf-8")
    click.echo(f"Script saved: {out_path} ({len(dialogue)} turns)")


@main.command()
def feed():
    """Regenerate the RSS feed from existing episodes."""
    from .feed import build_rss
    from datetime import datetime, timezone, timedelta

    config, root = load_config()
    paths = config.resolve_paths(root)
    output_dir = paths["output"]

    episodes = sorted(output_dir.glob("*.mp3"))
    if not episodes:
        click.echo("No episodes found in output directory.")
        return

    tz = timezone(timedelta(hours=8))
    ep_list = []
    for i, ep_path in enumerate(episodes):
        notes_path = paths["scripts"] / f"{ep_path.stem}_notes.txt"
        description = notes_path.read_text(encoding="utf-8") if notes_path.exists() else f"{config.podcast.title} - {ep_path.stem}"

        ep_list.append({
            "title": f"EP{i + 1:02d}: {ep_path.stem.replace('-', ' ').replace('_', ' ').title()}",
            "description": description,
            "audio_file": str(ep_path),
            "audio_url": f"{config.feed.audio_base_url}/{ep_path.name}",
            "pub_date": datetime.now(tz) - timedelta(days=len(episodes) - i - 1),
            "episode_number": i + 1,
        })

    rss_xml = build_rss(ep_list, config)
    feed_path = root / config.feed.output
    feed_path.write_text(rss_xml, encoding="utf-8")
    click.echo(f"RSS feed updated: {len(ep_list)} episodes → {feed_path}")
