"""CLI entry point: podcraft init / publish / script / feed."""

import json
import shutil
from pathlib import Path

import click

from .config import PodcraftConfig, load_config, CONFIG_FILENAME, DEFAULT_VOICES

TEMPLATES_DIR = Path(__file__).parent / "templates"


@click.group()
@click.version_option(package_name="podcraft")
def main():
    """PodCraft - Turn any Markdown into a two-person dialogue podcast."""
    pass


@main.command()
@click.option("--language", "-l", default="en", help="Podcast language (en, zh, ja)")
@click.option("--title", "-t", default="My Podcast", help="Podcast title")
def init(language: str, title: str):
    """Initialize a new PodCraft project in the current directory."""
    config_path = Path.cwd() / CONFIG_FILENAME
    if config_path.exists():
        click.echo(f"  {CONFIG_FILENAME} already exists. Aborting.")
        return

    lang_short = language[:2]
    voices = DEFAULT_VOICES.get(lang_short, DEFAULT_VOICES["en"])

    if lang_short == "zh":
        host_name, guest_name = "小刘", "美美"
        desc = f"由 PodCraft 生成的播客。"
    elif lang_short == "ja":
        host_name, guest_name = "タロウ", "ハナコ"
        desc = f"PodCraftで生成されたポッドキャスト。"
    else:
        host_name, guest_name = "Alex", "Sam"
        desc = f"A podcast generated by PodCraft."

    config_content = f"""podcast:
  title: "{title}"
  description: "{desc}"
  author: ""
  language: "{language}"
  category: "Technology"
  link: ""
  cover_url: ""

hosts:
  host:
    name: "{host_name}"
    voice: "{voices['host']}"
  guest:
    name: "{guest_name}"
    voice: "{voices['guest']}"

llm:
  engine: "gemini"       # gemini, anthropic, openai, auto
  model: ""              # empty = default per engine
  temperature: 0.7

tts:
  engine: "edge"         # edge (free), volcano_podcast (paid, high quality)
  silence_duration: 1.5
  sample_rate: 44100
  bitrate: "192k"

cover:
  engine: "disabled"     # disabled | placeholder (no API) | imagen (Gemini Imagen 4)
  size: 1400
  overlay:
    title: "{title}"
    subtitle: ""
    title_font_size: 80
    subtitle_font_size: 28
    title_color: [212, 175, 105]
    subtitle_color: [180, 155, 100]
  # theme_keywords:      # optional: map keywords in episode title to custom Imagen prompts
  #   "music": "Abstract sound waves and musical notes, artistic, no text"
  #   "tech": "Futuristic circuit patterns, blue tones, no text"

shownotes:
  enabled: true
  max_tokens: 1500
  temperature: 0.5

release:
  enabled: false         # set to true to upload audio to GitHub Releases
  repo: ""               # "owner/repo" — auto-detected from git remote if empty
  tag: "v1.0.0-podcast"

feed:
  audio_base_url: ""     # URL where your MP3s are hosted
  output: "podcast-feed.xml"

paths:
  output: "output/"
  scripts: "scripts/"
  prompts: "prompts/"
"""
    config_path.write_text(config_content, encoding="utf-8")

    # Create directories
    for d in ["output", "scripts", "prompts", "episodes"]:
        (Path.cwd() / d).mkdir(exist_ok=True)

    # Copy language-appropriate prompt templates
    src_template = TEMPLATES_DIR / f"system_{lang_short}.md"
    if not src_template.exists():
        src_template = TEMPLATES_DIR / "system_en.md"
    shutil.copy2(src_template, Path.cwd() / "prompts" / "system.md")

    src_notes = TEMPLATES_DIR / f"shownotes_{lang_short}.md"
    if not src_notes.exists():
        src_notes = TEMPLATES_DIR / "shownotes_en.md"
    if src_notes.exists():
        shutil.copy2(src_notes, Path.cwd() / "prompts" / "shownotes.md")

    click.echo(f"  Initialized PodCraft project ({language})")
    click.echo(f"  Created: {CONFIG_FILENAME}, prompts/system.md, prompts/shownotes.md")
    click.echo(f"\n  Next steps:")
    click.echo(f"  1. Export your LLM API key: export GEMINI_API_KEY=...")
    click.echo(f"  2. Put a Markdown file in episodes/")
    click.echo(f"  3. Run: podcraft publish episodes/your-doc.md")


@main.command()
@click.argument("input_file")
@click.option("--title", "-t", default="", help="Episode title")
@click.option("--episode-num", "-n", type=int, default=0, help="Episode number")
@click.option("--focus", "-f", default="", help="Focus areas for script generation")
def publish(input_file: str, title: str, episode_num: int, focus: str):
    """Publish a podcast episode from a Markdown file."""
    from .pipeline import publish as run_publish

    config, root = load_config()
    run_publish(input_file, config, root, title, episode_num, focus)


@main.command()
@click.argument("input_file")
@click.option("--output", "-o", default="", help="Output script path")
@click.option("--focus", "-f", default="", help="Focus areas")
def script(input_file: str, output: str, focus: str):
    """Generate a dialogue script from a Markdown file (no audio)."""
    from .script import generate_script as gen_script
    from .utils import read_document, slugify

    config, root = load_config()
    paths = config.resolve_paths(root)
    scripts_dir = paths["scripts"]
    scripts_dir.mkdir(parents=True, exist_ok=True)

    content = read_document(input_file)
    if len(content) > 120000:
        content = content[:120000]

    click.echo(f"Generating script from {input_file} ({len(content)} chars)...")
    dialogue = gen_script(content, config, root, focus)

    if output:
        out_path = Path(output)
    else:
        slug = slugify(Path(input_file).stem)
        out_path = scripts_dir / f"{slug}_script.json"

    out_path.write_text(json.dumps(dialogue, ensure_ascii=False, indent=2), encoding="utf-8")
    click.echo(f"Script saved: {out_path} ({len(dialogue)} turns)")


@main.command()
@click.argument("topic", required=False, default="")
@click.option("--description", "-d", default="", help="Topic description for targeted search")
@click.option("--output", "-o", default="", help="Output file path (default: episodes/<slug>.md)")
@click.option("--queries", "-q", multiple=True, help="Custom search queries (repeat for multiple)")
def research(topic: str, description: str, output: str, queries: tuple):
    """Research a topic via web search and generate a Markdown research document."""
    from .research import research_topic
    from .utils import slugify

    config, root = load_config()

    if not config.research.enabled:
        click.echo("  Research is disabled. Set research.enabled: true in podcraft.yaml.")
        return

    if not topic:
        click.echo("  Please provide a topic: podcraft research \"Your Topic\"")
        return

    click.echo(f"Researching: {topic}")
    search_queries = list(queries) if queries else None
    result = research_topic(topic, config, root, search_queries, description)

    if output:
        out_path = Path(output)
    else:
        episodes_dir = root / "episodes"
        episodes_dir.mkdir(exist_ok=True)
        out_path = episodes_dir / f"{slugify(topic)}.md"

    out_path.write_text(result, encoding="utf-8")
    click.echo(f"Research saved: {out_path} ({len(result)} chars)")


@main.command("auto-publish")
@click.option("--queue", "-q", default="publish-queue.json", help="Queue file path")
def auto_publish(queue: str):
    """Publish the next episode from the publish queue."""
    from .queue import get_next, pop_queue
    from .pipeline import publish as run_publish

    config, root = load_config()
    queue_path = root / queue

    item = get_next(queue_path)
    if not item:
        click.echo("  Queue is empty.")
        return

    episode_num = item.get("episode", 0)
    title = item.get("title", "")
    research_file = item.get("research_file", "")

    click.echo(f"Next in queue: {title}")

    # Check research file exists
    if research_file:
        research_path = root / research_file
        if not research_path.exists():
            click.echo(f"  Research file not found: {research_path}")
            click.echo("  Run 'podcraft research' first or check the path in publish-queue.json.")
            return
        input_path = str(research_path)
    else:
        click.echo("  No research_file in queue item. Cannot publish.")
        return

    result = run_publish(input_path, config, root, title, episode_num)

    # Only pop queue if publishing fully succeeded.
    # If release is enabled, require audio_url; otherwise, require audio_file.
    success = bool(result.get("audio_url")) if config.release.enabled else bool(result.get("audio_file"))
    if success:
        popped = pop_queue(queue_path)
        click.echo(f"  Popped from queue: {popped.get('title', '')}")
        from .queue import queue_length
        remaining = queue_length(queue_path)
        click.echo(f"  Queue remaining: {remaining}")
    else:
        click.echo("  Publish incomplete — queue not popped. Fix the issue and retry.")


@main.command()
@click.option("--rebuild", is_flag=True, help="Rebuild manifest from existing MP3 files (migration helper)")
def feed(rebuild: bool):
    """Regenerate the RSS feed from the episode manifest."""
    from .feed import build_rss
    from .manifest import load_manifest, save_manifest, MANIFEST_FILENAME
    from datetime import datetime, timezone, timedelta

    config, root = load_config()
    paths = config.resolve_paths(root)
    output_dir = paths["output"]
    manifest_path = output_dir / MANIFEST_FILENAME

    if rebuild:
        _rebuild_manifest(config, paths, manifest_path)

    episodes = load_manifest(manifest_path)
    if not episodes:
        click.echo("No episodes in manifest. Use --rebuild to create from existing files.")
        return

    tz = timezone(timedelta(hours=8))
    ep_list = []
    for ep in episodes:
        pub_date = ep.get("pub_date", "")
        if isinstance(pub_date, str) and pub_date:
            pub_date = datetime.fromisoformat(pub_date)
        else:
            pub_date = datetime.now(tz)

        ep_list.append({
            "title": ep["title"],
            "description": ep.get("description", ""),
            "audio_file": ep["audio_file"],
            "audio_url": ep.get("audio_url", ""),
            "pub_date": pub_date,
            "episode_number": ep["episode_number"],
        })

    rss_xml = build_rss(ep_list, config)
    feed_path = root / config.feed.output
    feed_path.write_text(rss_xml, encoding="utf-8")
    click.echo(f"RSS feed updated: {len(ep_list)} episodes → {feed_path}")


def _rebuild_manifest(config, paths, manifest_path):
    """Rebuild manifest from existing MP3 files and show notes."""
    import re
    from .manifest import save_manifest
    from datetime import datetime, timezone, timedelta

    output_dir = paths["output"]
    scripts_dir = paths["scripts"]

    mp3_files = sorted(
        f for f in output_dir.glob("*.mp3")
        if "silence" not in f.name and "test" not in f.name
    )

    if not mp3_files:
        click.echo("No MP3 files found to rebuild from.")
        return

    tz = timezone(timedelta(hours=8))
    episodes = []
    for ep_path in mp3_files:
        stem = ep_path.stem

        # Try to parse episode number from filename (ep06-xxx or module-N-xxx)
        ep_match = re.match(r"ep(\d+)", stem)
        mod_match = re.match(r"module-(\d+)", stem)
        if ep_match:
            ep_num = int(ep_match.group(1))
        elif mod_match:
            ep_num = int(mod_match.group(1))
        else:
            click.echo(f"  Skipping (can't parse episode number): {ep_path.name}")
            continue

        # Build title from filename
        if ep_match:
            name_part = stem[len(ep_match.group(0)):].lstrip("-").replace("-", " ").replace("_", " ")
            title = f"EP{ep_num:02d}: {name_part}" if name_part else f"EP{ep_num:02d}"
        else:
            name_part = stem[len(mod_match.group(0)) + 1:].lstrip("-").replace("-", " ").replace("_", " ").title()
            title = f"EP{ep_num:02d}: {name_part}" if name_part else f"EP{ep_num:02d}"

        notes_path = scripts_dir / f"{stem}_notes.txt"
        description = (
            notes_path.read_text(encoding="utf-8")
            if notes_path.exists()
            else f"{config.podcast.title} - {title}"
        )

        audio_url = f"{config.feed.audio_base_url}/{ep_path.name}" if config.feed.audio_base_url else ""

        episodes.append({
            "title": title,
            "episode_number": ep_num,
            "audio_file": str(ep_path),
            "audio_url": audio_url,
            "description": description,
            "pub_date": datetime.now(tz).isoformat(),
            "cover_file": "",
        })

    save_manifest(manifest_path, episodes)
    click.echo(f"Manifest rebuilt: {len(episodes)} episodes → {manifest_path}")
