"""Configuration management: podcraft.yaml + environment variables."""

import os
from dataclasses import dataclass, field
from pathlib import Path

import yaml


# Default Edge TTS voices per language
DEFAULT_VOICES = {
    "zh": {"host": "zh-CN-YunxiNeural", "guest": "zh-CN-XiaoxiaoNeural"},
    "en": {"host": "en-US-GuyNeural", "guest": "en-US-JennyNeural"},
    "ja": {"host": "ja-JP-KeitaNeural", "guest": "ja-JP-NanamiNeural"},
}

CONFIG_FILENAME = "podcraft.yaml"


@dataclass
class HostConfig:
    name: str = "Alex"
    voice: str = ""


@dataclass
class PodcastConfig:
    title: str = "My Podcast"
    description: str = "A podcast generated by PodCraft."
    author: str = ""
    email: str = ""
    language: str = "en"
    category: str = "Technology"
    link: str = ""
    cover_url: str = ""


@dataclass
class LLMConfig:
    engine: str = "gemini"
    model: str = ""
    temperature: float = 0.7
    max_output_tokens: int = 16384


@dataclass
class TTSConfig:
    engine: str = "edge"
    silence_duration: float = 1.5
    sample_rate: int = 44100
    bitrate: str = "192k"


@dataclass
class FeedConfig:
    audio_base_url: str = ""
    output: str = "podcast-feed.xml"


@dataclass
class CoverConfig:
    engine: str = "disabled"   # disabled | placeholder | imagen
    size: int = 1400
    overlay: dict = field(default_factory=dict)
    theme_keywords: dict = field(default_factory=dict)
    prompt_template: str = ""  # custom Imagen prompt (Jinja2)


@dataclass
class ShowNotesConfig:
    enabled: bool = True
    max_tokens: int = 1500
    temperature: float = 0.5


@dataclass
class ReleaseConfig:
    enabled: bool = False
    repo: str = ""   # "owner/repo", auto-detected from git remote if empty
    tag: str = "v1.0.0-podcast"


@dataclass
class ResearchConfig:
    enabled: bool = False
    search_engine: str = "gemini_grounding"   # gemini_grounding | disabled
    max_searches: int = 3
    max_research_chars: int = 30000
    max_output_tokens: int = 8192
    temperature: float = 0.7


@dataclass
class PodcraftConfig:
    podcast: PodcastConfig = field(default_factory=PodcastConfig)
    host: HostConfig = field(default_factory=lambda: HostConfig(name="Alex"))
    guest: HostConfig = field(default_factory=lambda: HostConfig(name="Sam"))
    llm: LLMConfig = field(default_factory=LLMConfig)
    tts: TTSConfig = field(default_factory=TTSConfig)
    feed: FeedConfig = field(default_factory=FeedConfig)
    cover: CoverConfig = field(default_factory=CoverConfig)
    shownotes: ShowNotesConfig = field(default_factory=ShowNotesConfig)
    release: ReleaseConfig = field(default_factory=ReleaseConfig)
    research: ResearchConfig = field(default_factory=ResearchConfig)
    paths: dict = field(default_factory=lambda: {
        "output": "output/",
        "scripts": "scripts/",
        "prompts": "prompts/",
    })

    @property
    def language(self) -> str:
        return self.podcast.language

    def resolve_paths(self, root: Path) -> dict[str, Path]:
        return {k: (root / v).resolve() for k, v in self.paths.items()}

    def get_voices(self) -> dict[str, str]:
        lang = self.language[:2]
        defaults = DEFAULT_VOICES.get(lang, DEFAULT_VOICES["en"])
        return {
            "host": self.host.voice or defaults["host"],
            "guest": self.guest.voice or defaults["guest"],
        }


def _merge_dataclass(dc, data: dict):
    """Update a dataclass instance from a dict, ignoring unknown keys."""
    if not isinstance(data, dict):
        return
    for k, v in data.items():
        if hasattr(dc, k):
            attr = getattr(dc, k)
            if hasattr(attr, '__dataclass_fields__') and isinstance(v, dict):
                _merge_dataclass(attr, v)
            else:
                setattr(dc, k, v)


def load_config(path: Path | None = None) -> tuple[PodcraftConfig, Path]:
    """Load config from podcraft.yaml. Returns (config, project_root)."""
    if path is None:
        path = find_config()
    if path is None:
        raise FileNotFoundError(
            f"No {CONFIG_FILENAME} found. Run 'podcraft init' first."
        )

    root = path.parent
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}

    config = PodcraftConfig()

    # Map YAML sections to dataclass fields
    if "podcast" in raw:
        _merge_dataclass(config.podcast, raw["podcast"])
    if "hosts" in raw:
        if "host" in raw["hosts"]:
            _merge_dataclass(config.host, raw["hosts"]["host"])
        if "guest" in raw["hosts"]:
            _merge_dataclass(config.guest, raw["hosts"]["guest"])
    if "llm" in raw:
        _merge_dataclass(config.llm, raw["llm"])
    if "tts" in raw:
        _merge_dataclass(config.tts, raw["tts"])
    if "feed" in raw:
        _merge_dataclass(config.feed, raw["feed"])
    if "cover" in raw:
        _merge_dataclass(config.cover, raw["cover"])
    if "shownotes" in raw:
        _merge_dataclass(config.shownotes, raw["shownotes"])
    if "release" in raw:
        _merge_dataclass(config.release, raw["release"])
    if "research" in raw:
        _merge_dataclass(config.research, raw["research"])
    if "paths" in raw:
        config.paths.update(raw["paths"])

    # Apply voice defaults based on language
    voices = config.get_voices()
    if not config.host.voice:
        config.host.voice = voices["host"]
    if not config.guest.voice:
        config.guest.voice = voices["guest"]

    return config, root


def find_config() -> Path | None:
    """Walk up from cwd looking for podcraft.yaml."""
    current = Path.cwd()
    for parent in [current, *current.parents]:
        candidate = parent / CONFIG_FILENAME
        if candidate.exists():
            return candidate
    return None


def get_api_key(engine: str) -> str:
    """Get API key for the given LLM engine from environment."""
    keys = {
        "gemini": "GEMINI_API_KEY",
        "anthropic": "ANTHROPIC_API_KEY",
        "openai": "OPENAI_API_KEY",
    }
    env_var = keys.get(engine, "")
    value = os.environ.get(env_var, "")
    if not value:
        raise RuntimeError(
            f"{env_var} not set. Export it or add to .env file."
        )
    return value
